
spring.application.name=simple-chatgpt-web-boot

# hung: spring.mvc.servlet.path=/api
# Motivation:
# 1. All REST controllers live under /api -> keeps endpoints organized and versioning-friendly.
# 2. Allows Tomcat to serve static pages (like index.html) directly from webapp without interference.
spring.mvc.servlet.path=/api

# application.properties
logging.level.org.springframework=DEBUG
logging.level.simple.chatgpt.mapper=DEBUG

# database.properties
jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/chatgpt_db?useSSL=false
db.hostname=localhost
db.port=3306
db.name=chatgpt_db
db.username=root
db.password=ZAQ!zaq1

# openai api key
openai.api.key=sk-XXXXXXXXXXXXXXXXXXXX

