package simple.chatgpt.batch.step;

import java.time.format.DateTimeFormatter;

/*
 hung: generic constants for all batch jobs
*/
public final class BatchJobConstants {

    private BatchJobConstants() {}

    // hung: ExecutionContext keys
    public static final String CONTEXT_LIST_ID         = "LIST_ID";
    public static final String CONTEXT_LIST_NAME       = "LIST_NAME";        
    public static final String CONTEXT_LIST_FILE_PATH  = "LIST_FILE_PATH";   
    public static final String CONTEXT_USER_IDS        = "USER_IDS";
    public static final String CONTEXT_MEMBER_IDS      = "MEMBER_IDS";
    public static final String CONTEXT_BATCH_ID        = "BATCH_ID";
    public static final String DOWNLOAD_URL 		   = "DOWNLOAD_URL";

    // hung: User list specific constants
    public static final String DEFAULT_USER_LIST_NAME         = "My User List Generated By Job";
    public static final String DEFAULT_DESCRIPTION            = "My User List Generated By Job";
    public static final String USER_LIST_BASE_DIR             = "/data/user_lists";
    public static final String USER_LIST_FILENAME_PATTERN     = "generated_user_lists_%s.csv"; // timestamp placeholder
    public static final DateTimeFormatter TIMESTAMP_FORMATTER = DateTimeFormatter.ofPattern("yyyyMMdd_HHmm");
    public static final String DOWNLOAD_BASE_URL              = "/batch/downloads/";
}
