package simple.chatgpt.batch.job.userListJob;

import java.util.HashMap;
import java.util.Map;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.batch.core.ExitStatus;
import org.springframework.batch.core.StepContribution;
import org.springframework.batch.core.StepExecution;
import org.springframework.batch.core.listener.StepExecutionListenerSupport;
import org.springframework.batch.core.scope.context.ChunkContext;
import org.springframework.batch.core.step.tasklet.Tasklet;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import simple.chatgpt.pojo.batch.JobRequest;
import simple.chatgpt.pojo.management.UserManagementListPojo;
import simple.chatgpt.service.batch.JobRequestService;
import simple.chatgpt.service.management.UserManagementListService;

/*
| Step                    | Type    | Reason                             |
| ----------------------- | ------- | ---------------------------------- |
| Step1CreateBatchHeader  | Tasklet | Single DB insert, one-off          |
| Step2LoadUsers          | Chunk   | Multiple records, DB read/write    |
| Step3PopulateUserList   | Chunk   | Multiple records, DB insert        |
| Step4GenerateCsv        | Tasklet | One-off file creation              |
| Step5EncryptAndTransfer | Tasklet | One-off file encryption & transfer |
*/

@Component
public class Step1CreateBatchHeader extends StepExecutionListenerSupport implements Tasklet {

    private static final Logger logger = LogManager.getLogger(Step1CreateBatchHeader.class);

    @Autowired
    private UserManagementListService userManagementListService;

    @Autowired
    private JobRequestService jobRequestService;

    @Override
    public void beforeStep(StepExecution stepExecution) {
        logger.debug("Step1CreateBatchHeader beforeStep called");
    }

    @Override
    public RepeatStatus execute(StepContribution contribution, ChunkContext chunkContext) throws Exception {
        logger.debug("Step1CreateBatchHeader execute called");

        // ==========================================
        // STEP 1: Fetch live JobRequest (stage=100, status=SUBMITTED)
        // ==========================================
        JobRequest jobRequest = jobRequestService.getLiveJobRequestByJobName(UserListJobConfig.JOB_NAME);
        logger.debug("execute jobRequest={}", jobRequest);

        if (jobRequest == null) {
            logger.error("No live JobRequest found for jobName=UserListJob");
            throw new IllegalStateException("Live JobRequest not found for UserListJob");
        }

        // ==================================================
        // STEP 2: Create new UserManagementList
        // ==================================================
        UserManagementListPojo userList = new UserManagementListPojo();
        logger.debug("execute userList={}", userList);

        userList.setUserListName("My User List");
        userList.setOriginalFileName("uploaded_file.csv");
        userList.setFilePath("/data/user_lists/uploaded_file.csv");
        userList.setDescription("Generated by Step1CreateBatchHeader");

        UserManagementListPojo createdList = userManagementListService.create(userList);
        logger.debug("execute createdList={}", createdList);

        // ==================================================
        // STEP 3: Add userList to JobRequest stepData
        // ==================================================
        Map<String, Object> stepData = jobRequest.getStepData();
        if (stepData == null) {
            stepData = new HashMap<>();
        }
        stepData.put("userListId", createdList.getId());
        stepData.put("userListName", createdList.getUserListName());
        jobRequest.setStepData(stepData);

        logger.debug("execute updated jobRequest with userList stepData={}", jobRequest.getStepData());
        logger.debug("execute jobRequest after attaching userList={}", jobRequest);

        // ==================================================
        // STEP 4: Update JobRequest to processing_stage=200, processing_status=1
        // ==================================================
        jobRequest.setProcessingStage(200);
        jobRequest.setProcessingStatus(1);
        jobRequestService.update(jobRequest.getId(), jobRequest);
        logger.debug("execute updated jobRequest to stage=200 status=1 jobRequest={}", jobRequest);

        // ==================================================
        // STEP 5: Save JobRequest POJO to JobExecutionContext
        // ==================================================
        chunkContext.getStepContext()
                    .getStepExecution()
                    .getJobExecution()
                    .getExecutionContext()
                    .put(UserListJobConfig.CONTEXT_JOB_REQUEST, jobRequest);
        logger.debug("execute saved jobRequest to JobExecutionContext jobRequest={}", jobRequest);

        // ==================================================
        // STEP 6: Done
        // ==================================================
        logger.debug("Step1CreateBatchHeader execute finished");
        return RepeatStatus.FINISHED;
    }

    @Override
    public ExitStatus afterStep(StepExecution stepExecution) {
        logger.debug("Step1CreateBatchHeader afterStep called");
        logger.debug("afterStep stepExecution={}", stepExecution);
        logger.debug("Step1CreateBatchHeader finished with status {}", stepExecution.getStatus());
        return stepExecution.getExitStatus();
    }
}
