package simple.chatgpt.batch.job.userListJob;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.batch.core.ExitStatus;
import org.springframework.batch.core.StepContribution;
import org.springframework.batch.core.StepExecution;
import org.springframework.batch.core.listener.StepExecutionListenerSupport;
import org.springframework.batch.core.scope.context.ChunkContext;
import org.springframework.batch.core.step.tasklet.Tasklet;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import simple.chatgpt.pojo.management.UserManagementListPojo;
import simple.chatgpt.service.management.UserManagementListService;

/*
| Step                    | Type    | Reason                             |
| ----------------------- | ------- | ---------------------------------- |
| Step1CreateBatchHeader  | Tasklet | Single DB insert, one-off          |
| Step2LoadUsers          | Chunk   | Multiple records, DB read/write    |
| Step3PopulateUserList   | Chunk   | Multiple records, DB insert        |
| Step4GenerateCsv        | Tasklet | One-off file creation              |
| Step5EncryptAndTransfer | Tasklet | One-off file encryption & transfer |
*/

@Component
public class Step1CreateBatchHeader extends StepExecutionListenerSupport implements Tasklet {

    private static final Logger logger = LogManager.getLogger(Step1CreateBatchHeader.class);

    @Autowired
    private UserManagementListService userManagementListService;

    @Override
    public void beforeStep(StepExecution stepExecution) {
        logger.debug("Step1CreateBatchHeader beforeStep called");
    }

    @Override
    public RepeatStatus execute(StepContribution contribution, ChunkContext chunkContext) throws Exception {
        logger.debug("Step1CreateBatchHeader execute called");

        // Create a new user list
        UserManagementListPojo userList = new UserManagementListPojo();
        userList.setUserListName("My User List");
        userList.setOriginalFileName("uploaded_file.csv");
        userList.setFilePath("/data/user_lists/uploaded_file.csv");
        userList.setDescription("Generated by Step1CreateBatchHeader");

        // Persist the list using UserManagementListService
        UserManagementListPojo createdList = userManagementListService.create(userList);
        Long listId = createdList.getId();
        logger.debug("Created user list with ID={}", listId);

        // Store listId in JobExecutionContext for downstream steps
        chunkContext.getStepContext()
                    .getStepExecution()
                    .getJobExecution()
                    .getExecutionContext()
                    .putLong("LIST_ID", listId);

        return RepeatStatus.FINISHED;
    }

    @Override
    public ExitStatus afterStep(StepExecution stepExecution) {
        logger.debug("Step1CreateBatchHeader finished with status {}", stepExecution.getStatus());
        return stepExecution.getExitStatus();
    }
}
